#! /bin/sh
### BEGIN INIT INFO
# Provides:          neutron-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      mysql postgresql rabbitmq-server keystone
# Should-Stop:       mysql postgresql rabbitmq-server keystone
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: neutron-server
# Description:       Provides the Neutron networking service
### END INIT INFO

export PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="OpenStack Neutron Server"
NAME=neutron-server
DAEMON=/usr/bin/${NAME}
PIDFILE=/var/run/neutron/${NAME}.pid
SCRIPTNAME=/etc/init.d/${NAME}
LOGFILE=/var/log/neutron/neutron-server.log
DAEMON_DIR=/var/run
DAEMON_ARGS="--config-file=/etc/neutron/neutron.conf"

# Exit if the package is not installed
[ -x $DAEMON ] || exit 0

. /lib/lsb/init-functions

[ -r /etc/default/openstack ] && . /etc/default/openstack
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

[ "x$USE_SYSLOG" = "xyes" ] && DAEMON_ARGS="$DAEMON_ARGS --use-syslog"
[ "x$USE_LOGFILE" != "xno" ] && DAEMON_ARGS="$DAEMON_ARGS --log-file=$LOGFILE"

[ -r /usr/share/neutron-common/plugin_guess_func ] || exit 0
. /usr/share/neutron-common/plugin_guess_func

### Maintain the plugin selection so that we can load the corresponding .ini file ###
if ! [ -r /etc/neutron/neutron.conf ] ; then
	echo "Cloud not read /etc/neutron/neutron.conf: exiting"
	exit 0
fi

CURRENT_PLUGIN=`grep "^[ \t]*core_plugin[ \t]*=[ \t]*[._a-zA-Z0-9]*\$" /etc/neutron/neutron.conf | sed -e 's/^[ \t]*core_plugin[ \t]*=[ \t]*//'`
if [ -z "${CURRENT_PLUGIN}" ] ; then
	echo "No core_plugin= value found: please set it and try again"
	exit 0
fi
neutron_core_plugin_to_plugin_name ${CURRENT_PLUGIN}
neutron_plugin_ini_path ${NEUTRON_PLUGIN_NAME}
if [ -z "${NEUTRON_PLUGIN_CONFIG}" ] ; then
	echo "Plugin not recognized: please edit /etc/init.d/neutron-server to select the correct .ini file to load for your plugin"
else
	DAEMON_ARGS="${DAEMON_ARGS} --config-file=${NEUTRON_PLUGIN_CONFIG}"
	DESC="${DESC} with ${NEUTRON_PLUGIN_NAME} plugin"
fi

### Neutron folders creation ###
make_neutron_folder () {
	if [ ! -e ${1} ] ; then
		mkdir -p ${1}
		if [ ! -d ${1} ] ; then
			echo "${1} folder cannot be created: exiting!"
			exit 1
		fi
		chown neutron:neutron ${1}
	fi
}
for i in /var/run/neutron /var/log/neutron /var/lib/neutron/tmp ; do
	make_neutron_folder ${i}
done
export TMPDIR=/var/lib/neutron/tmp

### Standard init script start/stop/etc. stuff ###
do_start () {
	start-stop-daemon --start --quiet --background --chuid neutron:neutron --chdir $DAEMON_DIR --make-pidfile --pidfile $PIDFILE --startas $DAEMON --test > /dev/null \
		|| return 1
	start-stop-daemon --start --quiet --background --chuid neutron:neutron --chdir $DAEMON_DIR --make-pidfile --pidfile $PIDFILE --startas $DAEMON -- \
		$DAEMON_ARGS \
		|| return 2
}

do_stop () {
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
	RETVAL="$?"
	rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) log_end_msg 1 ;;
	esac
;;
stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) log_end_msg 0 ;;
		*) log_end_msg 1 ;;
	esac
;;
restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	0|1)
		do_start
		case "$?" in
		0) log_end_msg 0 ;;
		1) log_end_msg 1 ;; # Old process is still running
		*) log_end_msg 1 ;; # Failed to start
		esac
	;;
	*)
		# Failed to stop
		log_end_msg 1
		;;
	esac
;;
status)
	status_of_proc -p $PIDFILE $DAEMON neutron-server && exit 0 || exit $?
;;
systemd-start)
    do_start
;;
systemd-stop)
    do_stop
;;
*)
	log_action_msg "Usage: /etc/init.d/neutron-server {start|stop|restart|force-reload|status}"
	exit 1
;;
esac

exit 0
