#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	if [ -f /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		db_get neutron-plugin-openvswitch/configure_db
		if [ "$RET" = "true" ]; then
			if [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
				. /usr/share/dbconfig-common/dpkg/postrm
				dbc_go neutron-plugin-openvswitch $@
			else
				rm -f /etc/dbconfig-common/neutron-plugin-openvswitch.conf
				if which ucf >/dev/null 2>&1; then
					ucf --purge /etc/dbconfig-common/neutron-plugin-openvswitch.conf
					ucfr --purge neutron-plugin-openvswitch /etc/dbconfig-common/neutron-plugin-openvswitch.conf
				fi
			fi
		fi
	fi
	[ -w /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini ] && rm -f /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
	[ -d /etc/neutron/plugins/openvswitch ] && rmdir --ignore-fail-on-non-empty /etc/neutron/plugins/openvswitch
	[ -d /etc/neutron/plugins ] && rmdir --ignore-fail-on-non-empty /etc/neutron/plugins
	[ -d /etc/neutron ] && rmdir --ignore-fail-on-non-empty /etc/neutron
	rm -rf /var/lib/neutron-plugin-openvswitch
fi

#DEBHELPER#

exit 0
