#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	# Purge db on purge
	if [ -f /usr/share/debconf/confmodule ] ; then
		. /usr/share/debconf/confmodule
		db_get neutron/configure_db
		if [ "$RET" = "true" ] ; then
			if [ -f /usr/share/dbconfig-common/dpkg/postrm ] ; then
				. /usr/share/dbconfig-common/dpkg/postrm
				dbc_go neutron-common $@
			else
				rm -f /etc/dbconfig-common/neutron-common.conf
				if which ucf >/dev/null 2>&1; then
					ucf --purge /etc/dbconfig-common/neutron-common.conf
					ucfr --purge neutron-common /etc/dbconfig-common/neutron-common.conf
				fi
			fi
		fi
	fi

	# Clean /etc/neutron on purge
	rm -f /etc/default/neutron /etc/neutron/api-paste.ini /etc/neutron/neutron.conf \
			/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
	[ -d /etc/neutron/plugins/openvswitch ] && rmdir --ignore-fail-on-non-empty /etc/neutron/plugins/openvswitch
	[ -d /etc/neutron/plugins ] 		&& rmdir --ignore-fail-on-non-empty /etc/neutron/plugins
	[ -d /etc/neutron ] 			&& rmdir --ignore-fail-on-non-empty /etc/neutron
        rm -rf /var/lib/neutron
        rm -rf /var/log/neutron
fi

#DEBHELPER#
