#! /bin/sh
### BEGIN INIT INFO
# Provides:          neutron-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      mysql postgresql rabbitmq-server keystone
# Should-Stop:       mysql postgresql rabbitmq-server keystone
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: neutron-server
# Description:       Provides the Neutron networking service
### END INIT INFO

export PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="OpenStack Neutron Server"
NAME=neutron-server
DAEMON=/usr/bin/${NAME}
PIDFILE=/var/run/neutron/${NAME}.pid
SCRIPTNAME=/etc/init.d/${NAME}
LOGFILE=/var/log/neutron/neutron-server.log
DAEMON_DIR=/var/run
DAEMON_ARGS="--config-file=/etc/neutron/neutron.conf --log-file=$LOGFILE"

# Exit if the package is not installed
[ -x $DAEMON ] || exit 0

. /lib/lsb/init-functions

### Guess the plugin name depending on the class of the plugin in /etc/neutron/neutron.conf ###
neutron_core_plugin_to_plugin_name () {
	case ${1} in
	"neutron.plugins.openvswitch.ovs_neutron_plugin.OVSNeutronPluginV2")
		NEUTRON_PLUGIN_NAME=OpenVSwitch
	;;
	"neutron.plugins.linuxbridge.lb_neutron_plugin.LinuxBridgePluginV2")
		NEUTRON_PLUGIN_NAME=LinuxBridge
	;;
	"neutron.plugins.ryu.ryu_neutron_plugin.RyuNeutronPluginV2")
		NEUTRON_PLUGIN_NAME=RYU
	;;
	"neutron.plugins.plumgrid.plumgrid_nos_plugin.plumgrid_plugin.NeutronPluginPLUMgridV2")
		NEUTRON_PLUGIN_NAME=PLUMgrid
	;;
	"neutron.plugins.brocade.NeutronPlugin.BrocadePluginV2")
		NEUTRON_PLUGIN_NAME=Brocade
	;;
	"neutron.plugins.hyperv.hyperv_neutron_plugin.HyperVNeutronPlugin")
		NEUTRON_PLUGIN_NAME=Hyper-V
	;;
	"neutron.plugins.bigswitch.plugin.NeutronRestProxyV2")
		NEUTRON_PLUGIN_NAME=BigSwitch
	;;
	"neutron.plugins.cisco.network_plugin.PluginV2")
		NEUTRON_PLUGIN_NAME=Cisco
	;;
	"neutron.plugins.nicira.NeutronPlugin.NvpPluginV2")
		NEUTRON_PLUGIN_NAME=neutron.plugins.nicira.NeutronPlugin.NvpPluginV2
	;;
	"neutron.plugins.midonet.plugin.MidonetPluginV2")
		NEUTRON_PLUGIN_NAME=Midonet
	;;
	"neutron.plugins.nec.nec_plugin.NECPluginV2")
		NEUTRON_PLUGIN_NAME=Nec
	;;
	"neutron.plugins.metaplugin.meta_neutron_plugin.MetaPluginV2")
		NEUTRON_PLUGIN_NAME=MetaPlugin
	;;
	"neutron.plugins.mlnx.mlnx_plugin.MellanoxEswitchPlugin")
		NEUTRON_PLUGIN_NAME=Mellanox
	;;
	*)
		NEUTRON_PLUGIN_NAME="other"
	;;
	esac
}

### Guess the path of the plugin .ini file depending on the plugin name ###
neutron_plugin_ini_path () {
	PLUG_INI_BASE=/etc/neutron/plugins/
	case ${1} in
	"OpenVSwitch")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}openvswitch/ovs_neutron_plugin.ini
	;;
	"LinuxBridge")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}linuxbridge/linuxbridge_conf.ini
	;;
	"RYU")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}ryu/ryu.ini
	;;
	"PLUMgrid")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}plumgrid/plumgrid.ini
	;;
	"Brocade")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}brocade/brocade.ini
	;;
	"Hyper-V")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}hyperv/hyperv_neutron_plugin.ini
	;;
	"BigSwitch")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}bigswitch/restproxy.ini
	;;
	"Cisco")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}cisco/cisco_plugins.ini
	;;
	"Nicira")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}nicira/nvp.ini
	;;
	"Midonet")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}midonet/midonet.ini
	;;
	"Nec")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}nec/nec.ini
	;;
	"MetaPlugin")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}metaplugin/metaplugin.ini
	;;
	"Mellanox")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}mlnx/mlnx_conf.ini
	;;
	*)
		NEUTRON_PLUGIN_CONFIG=""
	;;
	esac
}

### Maintain the plugin selection so that we can load the corresponding .ini file ###
if ! [ -r /etc/neutron/neutron.conf ] ; then
	echo "Cloud not read /etc/neutron/neutron.conf: exiting"
	exit 0
fi

CURRENT_PLUGIN=`grep "^[ \t]*core_plugin[ \t]*=[ \t]*[._a-zA-Z0-9]*\$" /etc/neutron/neutron.conf | sed -e 's/^[ \t]*core_plugin[ \t]*=[ \t]*//'`
if [ -z "${CURRENT_PLUGIN}" ] ; then
	echo "No core_plugin= value found: please set it and try again"
	exit 0
fi
neutron_core_plugin_to_plugin_name ${CURRENT_PLUGIN}
neutron_plugin_ini_path ${NEUTRON_PLUGIN_NAME}
if [ -z "${NEUTRON_PLUGIN_CONFIG}" ] ; then
	echo "Plugin not recognized: please edit /etc/init.d/neutron-server to select the correct .ini file to load for your plugin"
else
	DAEMON_ARGS="${DAEMON_ARGS} --config-file=${NEUTRON_PLUGIN_CONFIG}"
	DESC="${DESC} with ${NEUTRON_PLUGIN_NAME} plugin"
fi

### Neutron folders creation ###
make_neutron_folder () {
	if [ ! -e ${1} ] ; then
		mkdir -p ${1}
		if [ ! -d ${1} ] ; then
			echo "${1} folder cannot be created: exiting!"
			exit 1
		fi
		chown neutron:neutron ${1}
	fi
}
for i in /var/run/neutron /var/log/neutron /var/lib/neutron/tmp ; do
	make_neutron_folder ${i}
done
export TMPDIR=/var/lib/neutron/tmp

### Standard init script start/stop/etc. stuff ###
do_start () {
	start-stop-daemon --start --quiet --background --chuid neutron:neutron --chdir $DAEMON_DIR --make-pidfile --pidfile $PIDFILE --startas $DAEMON --test > /dev/null \
		|| return 1
	start-stop-daemon --start --quiet --background --chuid neutron:neutron --chdir $DAEMON_DIR --make-pidfile --pidfile $PIDFILE --startas $DAEMON -- \
		$DAEMON_ARGS \
		|| return 2
}

do_stop () {
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
	RETVAL="$?"
	rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) log_end_msg 1 ;;
	esac
;;
stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) log_end_msg 0 ;;
		*) log_end_msg 1 ;;
	esac
;;
restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	0|1)
		do_start
		case "$?" in
		0) log_end_msg 0 ;;
		1) log_end_msg 1 ;; # Old process is still running
		*) log_end_msg 1 ;; # Failed to start
		esac
	;;
	*)
		# Failed to stop
		log_end_msg 1
		;;
	esac
;;
status)
	status_of_proc -p $PIDFILE $DAEMON neutron-server && exit 0 || exit $?
;;
*)
	log_action_msg "Usage: /etc/init.d/neutron-server {start|stop|restart|force-reload|status}"
	exit 1
;;
esac

exit 0
