#!/bin/sh

# Remember to also add any new plugin name into neutron-common.templates

# Please remember this function is also duplicated in debian/neutron-common.config.in
### Guess the plugin name depending on the class of the plugin in /etc/neutron/neutron.conf ###
neutron_core_plugin_to_plugin_name () {
	case ${1} in
	"neutron.plugins.ml2.plugin.Ml2Plugin"|"ml2")
		NEUTRON_PLUGIN_NAME=ml2
	;;
	"networking_plumgrid.neutron.plugins.plugin:NeutronPluginPLUMgridV2"|"plumgrid")
		NEUTRON_PLUGIN_NAME=plumgrid
	;;
	"midonet.neutron.plugin_v1:MidonetPluginV2"|"midonet")
		NEUTRON_PLUGIN_NAME=midonet
	;;
	"midonet.neutron.plugin_v2:MidonetPluginV2"|"midonet_v2")
		NEUTRON_PLUGIN_NAME=midonet_v2
	;;
	"networking_nec.nwa.l2.plugin:NECNWAL2Plugin"|"necnwa")
		NEUTRON_PLUGIN_NAME=nec
	;;
	"vmware_nsx.plugin:NsxMhPlugin"|"vmware")
		NEUTRON_PLUGIN_NAME=vmware
	;;
	*)
		NEUTRON_PLUGIN_NAME="other"
	;;
	esac
}

### Guess the path of the plugin .ini file depending on the plugin name ###
neutron_plugin_ini_path () {
	PLUG_INI_BASE=/etc/neutron/plugins/
	case ${1} in
	"ml2")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}ml2/ml2_conf.ini
	;;
	"plumgrid")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}plumgrid/plumgrid.ini
	;;
	"midonet")
		NEUTRON_PLUGIN_CONFIG=/etc/midonet/midonet.ini.v1
	;;
	"midonet_v2")
		NEUTRON_PLUGIN_CONFIG=/etc/midonet/midonet.ini.v2
	;;
	"nec")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}nec/nec.ini
	;;
	"vmware")
		NEUTRON_PLUGIN_CONFIG=${PLUG_INI_BASE}nsx/nsx.ini
	;;
	*)
		NEUTRON_PLUGIN_CONFIG=""
	;;
	esac
}
